# Generated by Django 4.0.6 on 2022-08-08 00:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('order_id', models.UUIDField()),
                ('amount_in_cents', models.BigIntegerField()),
                ('provider', models.IntegerField(choices=[(1, 'Razorpay')])),
                ('provider_id', models.UUIDField()),
                ('status', models.IntegerField(choices=[(10, 'Initiated'), (20, 'Processing'), (30, 'Success'), (40, 'Refunded'), (50, 'Failed'), (60, 'Flagged')], default=10)),
                ('currency', models.CharField(choices=[('INR', 'INR')], max_length=5)),
            ],
            options={
                'db_table': 'payments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RazorpayModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('pg_order_id', models.CharField(default=None, max_length=20, null=True)),
                ('user_order_id', models.CharField(max_length=20)),
                ('request_response', models.JSONField(default=None)),
                ('verification_response', models.JSONField(default=None)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
