# Generated by Django 4.0.6 on 2022-08-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaymodel',
            name='payment_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='razorpaymodel',
            name='signature',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='razorpaymodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Attempted'), (3, 'Failed'), (4, 'Paid'), (5, 'Refunded'), (6, 'Verification Failed')], null=True),
        ),
    ]
