# Generated by Django 4.0.6 on 2022-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_razorpaymodel_payment_id_razorpaymodel_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaymodel',
            name='amount_in_cents',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
