# Generated by Django 4.0.6 on 2022-08-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_razorpaymodel_verification_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpaymodel',
            name='request_response',
            field=models.JSONField(default=dict),
        ),
    ]
