# Generated by Django 4.0.6 on 2022-08-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_razorpaymodel_request_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsmodel',
            name='provider_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='razorpaymodel',
            name='payment_id',
            field=models.CharField(default='902b2642-e18f-4342-8817-96264190bd93', max_length=40),
            preserve_default=False,
        ),
    ]
