# Generated by Django 4.0.6 on 2022-07-30 22:44

import backend_api.fields.base_fields
import backend_api.validators
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('email_id', models.EmailField(max_length=100, unique=True, validators=[backend_api.validators.Validators.email_validator])),
                ('mobile', models.CharField(max_length=10, unique=True, validators=[backend_api.validators.Validators.mobile_validator])),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
            bases=(models.Model, backend_api.fields.base_fields.BaseFields),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
