# Generated by Django 4.0.6 on 2022-08-06 23:48

import backend_api.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackagesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=40)),
                ('status', models.IntegerField(choices=[('Active', 1), ('In Active', 2), ('Deleted', 3)], default=1)),
                ('list_price_in_cents', models.IntegerField(validators=[backend_api.validators.Validators.min_0_validator])),
                ('selling_price_in_cents', models.IntegerField(validators=[backend_api.validators.Validators.min_0_validator])),
                ('configuration', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'packages',
                'managed': True,
            },
        ),
    ]
