# Generated by Django 4.0.6 on 2022-08-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstransactionledgermodel',
            name='reference_type',
            field=models.IntegerField(choices=[(1, 'Order')]),
        ),
        migrations.AlterUniqueTogether(
            name='businesstransactionledgermodel',
            unique_together={('reference_type', 'reference_id')},
        ),
    ]
