# Generated by Django 4.0.6 on 2022-08-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_businesstransactionledgermodel_reference_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businesstransactionledgermodel',
            unique_together={('reference_type', 'reference_id', 'is_credit')},
        ),
    ]
