# Generated by Django 4.0.6 on 2022-08-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_businesstransactionledgermodel_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesstransactionledgermodel',
            old_name='amount_in_cents',
            new_name='credits',
        ),
        migrations.AddField(
            model_name='businesstransactionledgermodel',
            name='credits_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businesstransactionledgermodel',
            name='expiry_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='businesstransactionledgermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='businesstransactionledgermodel',
            name='created_by',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterIndexTogether(
            name='businesstransactionledgermodel',
            index_together={('business', 'is_active', 'is_deleted')},
        ),
    ]
