# Generated by Django 4.0.6 on 2022-08-07 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('user_id', models.UUIDField()),
                ('business_id', models.UUIDField()),
                ('order_id', models.CharField(max_length=15, unique=True)),
                ('list_price_in_cents', models.BigIntegerField()),
                ('offer_discount_in_cents', models.BigIntegerField()),
                ('coupon_discount_in_cents', models.BigIntegerField(default=0)),
                ('sale_price_in_cents', models.BigIntegerField()),
                ('status', models.IntegerField(choices=[(10, 'Created'), (20, 'Payment Processing'), (30, 'Payment Completed'), (40, 'Refunded'), (50, 'Payment Processed'), (60, 'Issue')], default=10)),
                ('package_id', models.UUIDField(null=True)),
                ('order_type', models.IntegerField(choices=[(1, 'Package Purchase'), (2, 'Recharge')])),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
    ]
